#### general settings
name: Doc_SR_x2_noise
use_tb_logger: true
model: sr
distortion: sr
scale: 2
gpu_ids: [0,1]

#### datasets
datasets:
  train:
    name: Shutter
    mode: LQGT
    dataroot_GT: /opt/app/data/train/GTx2.lmdb
    dataroot_LQ: /opt/app/data/train/LRx2_spoiled.lmdb

    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 8
    GT_size: 256
    rand_rot: 3 # [-3, 3] degrees
    use_flip: false
    use_rot: false
    color: gray
  val:
    name: Shutter_val
    mode: LQGT
    n_workers: 4  # per GPU
    dataroot_GT: /opt/app/data/val/GTx2.lmdb
    dataroot_LQ: /opt/app/data/val/LRx2_spoiled.lmdb
    color: gray
  # test:
  #   name: no_gt
  #   mode: LQ
  #   n_workers: 4  # per GPU
  #   dataroot_LQ: /opt/app/data/test
  #   color: gray
#### network structures
network_G:
  which_model_G: RRDBNet
  upsample_type: interpolate
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 23

network_F:
  which_model_F: efficientnet-b0-gray

  #which_model_F: VGG
  pretrained: /path/to/pretrained/efficientnet-b0-gray.model_best.pth.tar
  in_nc: 1
  use_bn: false
  use_input_norm: true
#### path
path:
  pretrain_model_G: /path/to/pretrained/model/xx0000_G.pth
  strict_load: true
  experiments_root: /opt/app/data/docsr/experiments/noise/x2
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optim_G: adam
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99

  lr_scheme: MultiStepLR
          # 5e-4, 2.5e-4, 1.25e-4, 6.25e-5, 3e-5  1.25e-4, 6.25e-5, 3e-5, 1.5e-5, 6.25e-6, 3e-6
          # 1e-3, 5e-4, 2.5e-4, 1.25e-4, 6.25e-5, 3e-5  1.25e-4, 6.25e-5, 3e-5, 1.5e-5, 6.25e-6, 3e-6
          # 2.5e-4, 1.25e-4, 6.25e-5, 3e-5  1.25e-4, 6.25e-5, 3e-5, 1.5e-5, 6.25e-6, 3e-6
  lr_steps: [10000, 50000, 90000, 170000, 270000, 300000, 400000]
  #restarts: [210000]
  #restart_weights: [0.2]
  niter: 500000
  warmup_iter: -1  # no warm up
  # lr_steps: [50000, 100000, 150000, 200000, 250000]
  lr_gamma: 0.5

  pixel_criterion: cb
  pixel_weight: !!float 1
  feature_criterion: p-cb
  feature_weight: !!float 1
  edge_criterion: cb
  edge_weight: !!float 5e-2

  manual_seed: 10
  val_freq: !!float 2e3
  #test_freq: !!float 1e4
#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
